import { LoggedInProvider } from "./LoginContext"
import MainButtonAppBar from "@/components/ButtonAppBar"


export const metadata = {
  title: 'Song App',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <LoggedInProvider>
          <MainButtonAppBar />
          {children}
        </LoggedInProvider>
      </body>
    </html>
  )
}
