import UserButton from "@/components/UserButton"
import { LoggedInProvider } from "./LoginContext"

export const metadata = {
  title: 'Song App',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <LoggedInProvider>
          {children}
          {/* <UserButton /> */}
        </LoggedInProvider>
      </body>
    </html>
  )
}
